# Generated by Django 4.2.5 on 2023-09-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sqft', models.IntegerField()),
                ('photo', models.ImageField(upload_to='property_photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
