# Generated by Django 4.2.5 on 2023-09-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0005_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
