# Generated by Django 4.2.5 on 2023-09-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0006_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.AddField(
            model_name='property',
            name='types',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
